apiVersion: v1
kind: Service
metadata:
  name: agentxport-frontend
  namespace: agentxport
  labels:
    app.kubernetes.io/name: agentxport-frontend
    app.kubernetes.io/part-of: agentxport
    app.kubernetes.io/component: frontend
    app.kubernetes.io/version: "1.0"
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: agentxport-frontend
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
